import type { Metadata } from "next";
import localFont from "next/font/local";
import {Host_Grotesk} from "next/font/google"

import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";

const nohemi = localFont({
  src: "./fonts/InterVariable.woff2",
	variable: "--font-sans",
	display: "swap",
});

const geistMono = localFont({
	src: "./fonts/GeistMono.woff2",
	variable: "--font-geist-mono",
	display: "swap",
  style:""
});

export const metadata: Metadata = {
	title: "Continuum",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={nohemi.variable} suppressHydrationWarning>
			<body className={`${nohemi.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
