import type { Metadata } from "next";
import localFont from "next/font/local";
import { QueryProvider } from "@/providers/query-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import "./globals.css";

// Load local fonts
const inter = localFont({
	src: "./fonts/InterVariable.woff2",
	variable: "--font-sans",
	display: "swap",
});

const geistMono = localFont({
	src: "./fonts/GeistMono.woff2",
	variable: "--font-geist-mono",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Continuum",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={inter.variable} suppressHydrationWarning>
			<body className={`${inter.variable} ${geistMono.variable} antialiased`}>
				<QueryProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						{children}
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
